jsperf/jsperf.com

- manifest.js
- package.json
- server/repositories/tests.js
- server/web/sitemap/xml.hbs
- server/web/sitemap/xml.js
- test/server/repositories/tests.js
- test/server/web/sitemap/xml.js
https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/sitemap.xml.tpl
> Add sitemap.xml

- manifest.js
- server/repositories/pages.js
- server/repositories/tests.js
- server/services/pages.js
- server/web/popular/index.hbs
- server/web/popular/index.js
- server/web/sitemap/xml.js
- test/server/repositories/pages.js
- test/server/repositories/tests.js
- test/server/services/pages.js
- test/server/web/popular/index.js
- test/server/web/sitemap/xml.js
show popular tests based on hits
https://github.com/maxbeatty/jsperf.com/blob/breakdown/_tpl/popular.tpl
> Add popular

- manifest.js
- package.json
- server/web/errors/400.hbs
- server/web/errors/403.hbs
- server/web/errors/404.hbs
- server/web/errors/general.hbs
- server/web/errors/index.js
- test/server/web/errors/index.js
> Add custom error pages.

- server/web/home/index.hbs
> Add quotes around user-supplied attribute values

- server/web/home/index.hbs
trying to reproduce failures of jsperf/jsperf.com#102 and fix jsperf/jsperf.com#88 at the same time
> reference slug directly

- npm-shrinkwrap.json
- package.json
- server/web/edit/index.js
Fix 'ui.benchmark' error and update shrinkwrap.
Depends on #113 
Issue #15
> Edit page minor 

- server/repositories/pages.js
- server/services/pages.js
- server/web/test/index-atom.hbs
- server/web/test/index.js
- test/server/repositories/pages.js
- test/server/services/pages.js
- test/server/web/test/index.js
Issue: Add test page atom feed #14 (milestone V2.1)
This atom feed gets & finds only visible pages.
> Test page Atom feed

- manifest.js
- templates/partials/header.hbs
- test/server/web/faq/index.js
- test/server/web/home/index.js
> Changes title-tag to the original behavior

- README.md
- manifest.js
- server/repositories/pages.js
- server/services/pages.js
- server/web/delete/index.hbs
- server/web/delete/index.js
- test/unit/server/repositories/pages.js
- test/unit/server/services/pages.js
- test/unit/server/web/delete/index.js
> Ability to delete tests

- .snyk
- manifest.js
- npm-shrinkwrap.json
- package.json
- server/web/test/index.hbs
- server/web/test/index.js
- test/unit/server/web/test/index.js
fixes #33 #46 
[scooter](https://github.com/hapijs/scooter/) is a thin hapijs plugin for [useragent](https://www.npmjs.com/package/useragent)
> use scooter to display user agent

- manifest.js
- npm-shrinkwrap.json
- package.json
- server/lib/schema.js
- server/repositories/tests.js
- server/web/edit/index.hbs
I started out trying to fix the rendering of prep code but quickly fell into a rabbit hole of issues
> fix form processing

- client/ui.js
- public/_js/test.js
the build process copied over in #158 doesn't build a working JS file. main issue is Benchmark.Suite not being a constructor. the `dist/all.js` published to npm appears to be working so I copied that over along with the id changes
> Fix test.js

- gulpfile.js
- public/_js/test.js
Ref. https://github.com/jsperf/benchmark.js-wrapper/commit/7729ba790c61821474ab2d46840f76408d270a15.
> Fix the `_js/test.js` build process

- gulpfile.js
> Disable minification for `test.js`

- docker/Dockerfile-lb
- docker/build-lb.sh
- docker/consul-template.service
- docker/nginx.conf
- docker/start-lb.sh
Addresses folder perms
Locks down nginx version
> Load balancer fix.

- templates/helpers/addCode.js
- test/unit/templates/helpers/addCode.js
> Support multiple code spans in test snippet titles

- package.json
- public/_js/test.js
Thanks to @demoneaux! Fixes #235.
> Work around the Browserscope embed issues in Chromium-based browsers

- server/api/json.js
- test/unit/server/api/json.js
Hi,
please check this PR.
Questions:
- how should I structure the API? (I personally just need this one method)
- auth? rate-limiting? api-keys?
- how to properly mock pages service?
- do you separate request validators and response mappers?
- how do you document the API?
> Initial version of the API to get page content

- package.json
This allows running `npm run deploy && now alias` to deploy and alias a new version.
> Add `now`-specific configuration to `package.json`

- server/repositories/browserscope.js
- server/services/pages.js
- test/unit/server/repositories/browserscope.js
- test/unit/server/services/pages.js
> log errors from browserscope instead of rejecting

- LICENSE-MIT.txt
> Add license

- package.json
> Add license identifier to package.json

- server/lib/schema.js
- server/repositories/tests.js
- server/web/edit/index.hbs
- server/web/edit/index.js
- server/web/test/index.hbs
- server/web/test/index.js
- test/unit/server/repositories/tests.js
as LeZuse/jsperf.com#1 identified, the `tests` table does not have an `id` field but rather a `testID` field. all of our references are wrong. Thanks @LeZuse for looking into this!!
I don't think this alone will resolve #153 or #236 but it's a start.
> tests do not have id field

- CONTRIBUTING.md
- README.md
- npm-shrinkwrap.json
- package.json
this eased my local development. hopefully it helps others, too
> watch for changes

- .gitignore
- .travis.yml
- CONTRIBUTING.md
- manifest.js
- package.json
- server/repositories/pages.js
- test/e2e/_helper.js
- test/e2e/home.js
- test/unit/server/repositories/pages.js
I created @1xTEST to be able to authenticate with GitHub without disabling my own 2FA.
By being able to run e2e locally to create pages this could satisfy #24 and #86
> add e2e test to login and create page

- client/ui.js
- public/_js/main.src.js
- public/_js/test.js
- server/lib/schema.js
- server/repositories/browserscope.js
- server/repositories/pages.js
- server/repositories/tests.js
- server/services/pages.js
- server/web/auth/github.js
- server/web/edit/index.hbs
- server/web/edit/index.js
- server/web/home/index.hbs
- server/web/home/index.js
- server/web/test/index.hbs
- server/web/test/index.js
- templates/partials/footer.hbs
- templates/partials/header.hbs
- test/e2e/home.js
- test/unit/server/repositories/pages.js
- test/unit/server/repositories/tests.js
- test/unit/server/services/pages.js
- test/unit/server/web/auth/github.js
- test/unit/server/web/auth/test.hbs
- test/unit/server/web/edit/index.js
- test/unit/server/web/home/index.js
- test/unit/server/web/test/index.js
> many fixes + some ✨

- templates/partials/footer.hbs
> Use teardown for the teardown segment

- README.md
- config.js
- manifest.js
- package-lock.json
- package.json
- server/lib/cache.js
- server/web/browse/index.js
- test/unit/server/web/browse/index.js
closes #136 
caching could be added to more places but will wait for performance bottlenecks. I used a free [Redis Labs](https://redislabs.com) instance which would likely suit our needs or running redis in a Docker container on Zeit.
> add caching

- .travis.yml
- Dockerfile
- now.json
- now.prod.json
- package.json
1. use Dockerfile for [v2 deploys](https://zeit.co/blog/serverless-docker)
2. clean up travis config 
3. separate now config for prod deploys so right secrets are used (`now -A now.prod.json`)
> add separate config for prod deploys

- vercel.json
modify vercel config to use vercel/node to run the hapi server
> vercel node config
